### ISSUE TITLE
Change the project's name

### ISSUE THREAD

**Issue by commandline** [commandline/clockwork-daydream#19]
No idea if github will through a fit or even allows renaming. A couple of reasons here. First, Atlassian may object to the name if the project acquires any kind of notice. Second, and more importantly, as I am working on this and thinking about its potential users and the value to them, something that better expresses how this is meant to extract from Jira (and maybe other tools down the road) and support Scrum Masters in reflecting data about a team's work over time back to them would be a much better choice.

**Comment by commandline** [comment]
Changed to clockwork daydream, riffing on some favorite song titles and lyrics. Speaks to automation and reflection, pondering. The two words are pretty unique as a project name on github, as a bonus.

**Comment by nchase** [comment]
:thumbsup:
